# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webno', '0004_auto_20170714_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
