# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webno', '0008_auto_20170714_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-createtime',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
